name: 3dcoin
version: '0.14.5.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.
grade: devel
confinement: devmode

apps:
  3dcoind:
    command: bin/3dcoind
  3dcoin-cli:
    command: bin/3dcoin-cli
  3dcoin-qt:
    command: bin/3dcoin-qt
    
parts:
  3dcoin:
    plugin: nil
    override-build: | 
      env | grep SNAP
      wget https://github.com/BlockchainTechLLC/3dcoin/releases/download/v0.14.5.1/3dcoin-x86_64-pc-linux-gnu-0.14.5.1.tar.gz
      tar -xvf 3dcoin-x86_64-pc-linux-gnu-0.14.5.1.tar.gz
      install -m 0755 -D -t 3dcoin-x86_64-pc-linux-gnu-0.14.5.1/bin/3dcoind
      install -m 0755 -D -t 3dcoin-x86_64-pc-linux-gnu-0.14.5.1/bin/3dcoin-qt
      install -m 0755 -D -t 3dcoin-x86_64-pc-linux-gnu-0.14.5.1/bin/3dcoin-cli
    build-packages:
      - wget
    after:
      - desktop-qt5
